### ISSUE TITLE
Help por conta da assinatura

### ISSUE THREAD

**Issue by quiteriadanno** [glaucia86/workshop-azure-fundamentals#1]
Gláucia, bom dia.

reciso de um help, estou tentando criar no QnA Maker para o ChatBot da nossa Etec e a conta do Centro Paula Souza esta sem assinatura, tentei entrar com o me Hotmail e solicita que crie uma assinatura que pode ser gratuita por 30 dias e preciso incluir dados do CC ou Débito.

Eu estava sem computador no dia, e não marquei como posso criar utilizando o voucher de professores.

1) Preciso criar uma conta gratuita?  Se sim, posso utilizar a minha conta pessoal do hotmail ao invés de utilizar da @etec ?  Neste caso, a conta depois de 30 dias será concelada sem custo?

Estou fazendo o curso de criação de ChatBot e esbarrei no mesmo problema.

Quitéria Danno.

**Comment by glaucia86** [comment]
> Gláucia, bom dia.
> 
> reciso de um help, estou tentando criar no QnA Maker para o ChatBot da nossa Etec e a conta do Centro Paula Souza esta sem assinatura, tentei entrar com o me Hotmail e solicita que crie uma assinatura que pode ser gratuita por 30 dias e preciso incluir dados do CC ou Débito.
> 
> Eu estava sem computador no dia, e não marquei como posso criar utilizando o voucher de professores.
> 
> 1. Preciso criar uma conta gratuita?  Se sim, posso utilizar a minha conta pessoal do hotmail ao invés de utilizar da @Etec ?  Neste caso, a conta depois de 30 dias será concelada sem custo?
> 
> Estou fazendo o curso de criação de ChatBot e esbarrei no mesmo problema.
> 
> Quitéria Danno.

Pode criar com a sua conta pessoal sem problemas. Já tentou o trial? Tenta o link abaixo

**[Link](https://aka.ms/AA55kfm)**


cc: @quiteriadanno
