### ISSUE TITLE
Erro no endereço: https://aka.ms/AA4qm7c

### ISSUE THREAD

**Issue by quiteriadanno** [glaucia86/workshop-azure-fundamentals#2]
Gláucia,

Esta dando erro 400 no endereço disponibilizado: https://aka.ms/AA4qm7c

Quitéria Danno.

**Comment by glaucia86** [comment]
Vou dar uma olhada... e já vou ajustar agora mesmo! 👍

**Comment by glaucia86** [comment]
Acertado para o endereço: https://aka.ms/AA55oxc

cc: @quiteriadanno
